# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WeiBoProject' do

pod 'AFNetworking'
pod 'BlocksKit'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'


end

target 'WeiBoProjectTests' do

end

target 'WeiBoProjectUITests' do

end

